name: Stocks

on:
  push:
    branches: [main]
  schedule:
    - cron: "5 10 * * 1-5"
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  Main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch stock data
        run: |
          python -c "import requests;
          
          session = requests.Session()
          session.headers.update({
              'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36'
          })
          session.get('https://www.nseindia.com/get-quotes/equity?symbol=TCS')
          response = session.get('https://www.nseindia.com/api/equity-stockIndices?index=NIFTY%20500')

          with open('stocks.json', 'w') as f:
              f.write(response.text)
          "

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - id: deployment
        uses: actions/deploy-pages@v4
